[package]
name = "oxiv_riscv32"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
oxiv_kernel = { workspace = true }

[[bin]]
name = "oxiv_riscv32"
path = "main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
